title: Cloud Study Network
description:
baseurl: ""
url: ""

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - old/
  - LICENSE
  - README.md

collections:
  authors:
    output: true
  posts:
    output: true
  events:
    output: true
  index:
    output: false

permalink: /:title/

defaults:
  - scope:
      path: ''
      type: posts
    values:
      layout: post
      permalink: /articles/:title/
  - scope:
      path: ''
      type: events
    values:
      layout: event
      subtitle:
      title:
      permalink: /events/:year/:month/:title/
  - scope:
      path: ''
      type: authors
    values:
      layout: author
      permalink: /members/:title/